### ISSUE TITLE
Disabling PayPal in MyAccount > Subscription > Change Payment 

### ISSUE THREAD

**Issue by hoobsi** [Prospress/woocommerce-subscriptions-disable-paypal#1]
Does anyone know how to get rid of PayPal in MyAccount > Subscription > Change Payment ? 
Otherwise everything seems to work perfectly well with this plugin!

**Comment by thenbrent** [comment]
Hi @hoobsi good question. That sounds like a bug in this plugin. Let me do up a fix for that quickly.

**Comment by thenbrent** [comment]
@hoobsi I've fixed this issue up with the commit SHA: 3c7a7b79fddb08e

You can download the latest version and it will now make sure PayPal isn't presented as a payment method on the **My Account > Subscription > Change Payment** page.
