### ISSUE TITLE
Disable PayPal for Subscriptions in Woocommerce 3.0

### ISSUE THREAD

**Issue by cnomadl** [Prospress/woocommerce-subscriptions-disable-paypal#2]
Hi, Will there be an update soon for this plugin as since the update of Woocommerce to 3.0 the plugin no longer disables Paypal for subscriptions.

**Comment by thenbrent** [comment]
@cnomadl thanks for the report. I'll look into it now. Can you also provide more details on what is not working specifically? i.e. is PayPal being incorrectly shown for a normal subscription product purchase? Or is it being incorrectly hidden for non-subscription product purchases? Or is it something to do with paying for renewal?

I can't see any reason from the code as to why it wouldn't work. But it is likely something has changed that could break it.

**Comment by thenbrent** [comment]
@cnomadl I've just deleted my previous comment. I see you have clarified what is not working. I'll look into it now. 👍

**Comment by thenbrent** [comment]
@cnomadl can you please also confirm you have Subscriptions v2.2.0 active? It's the version which offers WooCommerce 3.0 compatibility and was released very recently.

**Comment by thenbrent** [comment]
@cnomadl I can't reproduce this so I'm going to close it. Please make sure you have Subscriptions v2.2.0 active. If you still see the issue with that version, we can reopen and investigate further.

**Comment by cnomadl** [comment]
Just Checked and no I am using 2.1.4 I haven't renewed my subscription as of yet. Is this the cause?

**Comment by thenbrent** [comment]
@cnomadl most likely. Only Subscriptions v2.2.0 or newer is compatible with WooCommerce 3.0. WooCommerce changed (and broke) a lot of things in version 3.0 and any version of Subscriptions prior to v2.1.4 is very unlikely to work with it.

We had to make almost 10,000 changes to Subscriptions to be compatible with WooCommerce 3.0.
