### ISSUE TITLE
What happens to existing PP subscriptions?

### ISSUE THREAD

**Issue by TomasHurtz** [Prospress/woocommerce-subscriptions-disable-paypal#3]
Hi thanks for sharing this, I am going to use this because I want to sell products with Paypal, but remove it for subscriptions as it causes too many headaches.

However, do you know what happens to existing paypal subscriptions once I remove paypal?  Because PayPal sometimes automatically make payments anyway, so how do we get paypal to cancel all standing order subscriptions, once we disable it with your plugin?

Thank you

**Comment by james-allan** [comment]
Hi @TomasHurtz. Great question. 

Existing subscriptions with PayPal will continue to process with this plugin installed. What this plugin does is remove PayPal as a payment method option on the checkout if the cart contains a subscription. 

All the other PayPal code still comes packaged with the Subscriptions plugin and so will continue to process any existing PayPal IPN messages. I'll update this plugin's readme to include these extra details. 

Thanks.

**Comment by thenbrent** [comment]
For others coming to this in future, doc for this now here: https://github.com/Prospress/woocommerce-subscriptions-disable-paypal#exisitng-paypal-subscriptions :)

Added via https://github.com/Prospress/woocommerce-subscriptions-disable-paypal/commit/6904d4828ad961628500a4ddeefa844665810fc7

**Comment by TomasHurtz** [comment]
Hello @thenbrent  and @james-allan 

Thank you for the clarifications - so I understand existing subscriptions using PayPal will continue.  Your updated text on the rread me is helpful (but by the way, you should also modify the text at the top of readme:  

WooCommerce Subscriptions Disable PayPal
Using WooCommerce Subscriptions? Want to disable PayPal for subscription purchases, but still offer it for one-off products?

Install and activate this plugin. **_It will also disable PayPal for subscription renewal._**  <<<< THIS

Any idea how we can remove PayPal for existing subscriptions too ??

**Comment by thenbrent** [comment]
> Any idea how we can remove PayPal for existing subscriptions too ??

Hi @TomasHurtz the best approach for that can get tricky, and will likely depend in part on the payment gateway you want folks to migrate too. I'd recommend contacting [Prospress Support](https://prospress.com/support/) to ask for help with that.
